### ISSUE TITLE
Default Contributor Title in Preferences is misleading

### ISSUE THREAD

**Issue by Stephen-Gates** [qcif/data-curator#1036]
### Current Behaviour (for problems)
The default Contributor Title "Mr" in Preferences is misleading. The [spec](https://specs.frictionlessdata.io/data-package/#contributors) states that title is the, "name/title of the contributor (name for person, name/title of organization)".

E.g. "Stephen Gates" or "QCIF"

### Expected Behaviour
Suggest changing the default / hint text to something more reflective of the spec. 

### Steps to Reproduce

1. Open Data Curator 
2. Choose Preferences from the DataCurator menu (still missing a space "Data Curator")

### Your Environment

* Data Curator version: 1.2.0-alpha according to the About page but downloaded 1.2.5-beta
* Operating System and version: e.g. macOS 10.15.6

(Sorry about the multiple issues in here)

**Comment by mattRedBox** [comment]
@Stephen-Gates I don't appear to see any 'default' title for contributor in current and previous versions I have installed (e.g., 1.1), unless I've misunderstood this or I'm looking in the wrong place?
Could it be that you had 'Mr' set on your own install from previous use of Data Curator? (Preferences persist between Data Curator use. Please let me know (perhaps via screenshot) or attempt to delete what you have set in your Preferences and see what happens when you open DataCurator again.

**Comment by Stephen-Gates** [comment]
Apologies. you're correct @mattRedBox
