### ISSUE TITLE
Specify a custom attribute in the preferences menu that would display on the field screen

### ISSUE THREAD

**Issue by pripley123** [qcif/data-curator#988]
As a data provider
I want the ability to specify a custom attribute in the preferences menu that would display on the field screen
so that I could tailor the field metadata entry to my specific use case

Particular use case I'm thinking of:
As a data provider
I want the ability to set a variable classification (e.g., direct identifier, indirect identifier) for each field.
so that when my data is ingested the identifiers can be removed from other content automatically.  As well, when sending to other stakeholders for review, the variable classification is important piece of information to have along with the rest of the metadata (and it would be nice to have users specify the classification at the same time they're entering other metadata).

Could be implemented as a custom metadata attribute on the field metadata screen.  Which custom attributes to display could be configured on the Preferences page.  Would be nice if dropdown values for the custom attribute could be specified.

**Comment by mattRedBox** [comment]
Hi @pripley123 
Sorry I'm a little lost with this one. I'm assuming that the preference attribute would display in every field 'value' where the preference attribute is specified, substituting the attribute for the value at some point?

Again, it sounds like there might be more work involved here than #987 or #986, so I don't think it will make it for this release. But, if not too much trouble, is it possible to explain a little further (or provide examples/diagrams)?

**Comment by pripley123** [comment]
Thanks for the all the responses @mattRedBox .  So for this one, I was wanting to have a custom attribute displayed on the "Column" tab, so in my particular case an attribute called "Variable classification".  Ideally it would be a drop down of values.  So each column could have a value for variable classification.  So, I was proposing on the Preferences page to have an option of specifying a custom attribute that would display in the Column tab.  So, in my instance, I'd click "new custom attribute" and call it "Variable classification".   I'd also be able to specify possible values for my custom field (which would fill out the dropdown).  Hope that makes it clearer.

**Comment by mattRedBox** [comment]
Yes thanks @pripley123 
I think I've got it (well more of it) now.
So a User:
- Opens up preferences (or some other way perhaps) to create a custom Column Properties field 
- Then once this field is created, a means to enter various set values
- This new field, once created would appear in all columns, with the ability to select from the drop-down.
- The field attribute value isn't used in any table cell values at all, but is another piece of metadata for the column
- Like all column fields, it would then appear in the datapackage ->resource->schema->fields

Please let me know how close I'm getting now?
I'm thinking that if the above is correct, it's almost like having a foreign key setup but for the column properties themselves rather than column cell values

**Comment by mattRedBox** [comment]
Hi @pripley123 
At the moment we've shortlisted this idea with our sponsors. We'll be considering this and a small number of others in coming week or two.
